apiVersion: blameless/v1alpha
kind: SLO # Service Level Objective

metadata:
  name: string        # unique name of the SLO
  displayName: string # optional

  userJourney: string # name of the user journey to associate this SLO with - See spec for UserJourney

spec:
  description: string # optional - maps to user journey definition

  owner: string       # name of a user in your Blmameless account (e.g. user email)

  # SLO status (required)
  #    Error budget notification policy activated only in Testing and Active mode.
  #    SLO settings can only be changed in Development and Testing mode via the Blameless web console.
  sloStatus: development # possible values: development | testing | active

  sliName: string     # name of the SLI to apply this SLO to

  # objective
  target: 0.95        # reliability target for this SLO. Possible values: numeric [0.0, 1.0)

  # if SLI type is thresholdMetric type
  op: lt              # conditional operator used to compare the SLI against the value. Possible values: lte | gte | lt | gt
  value: numeric      # value used to compare metrics values (e.g. Latency)
  valueMetric: ms     # possible values: ms | s

  # required
  errorBudgetPolicyName: string # name of the error budget policy to attach to this SLO - See spec for AlertPolicy
