apiVersion: blameless/v1alpha
kind: SLI # Service Level Indicator

metadata:
  name: SLI Throughput-newrelic-throughput        # unique name of the SLI
  displayName: sli.yaml found at blameless-slo-samples/newrelic/throughput # optional

  service: Service-newrelic-throughput     # name of the service to associate this SLI with

spec:
  description: "source: http://blamelesshq/blameless-slo-sample/newrelic/throughput/sli.yaml" # optional - maps to user SLI definition in Blameless

  owner: nicolas@blameless.com       # name of a user in your Blameless account (e.g. user email)

  sliType: throughput        # possible values: availability | latency | throughput | saturation
  
  thresholdMetric:        # represents the metric used to inform the SLO in the objectives stanza
    source: newrelic     # data source for the metric
    queryType: string     # a name for the type of query to run on the data source
    query: SELECT count(*) FROM Public_APICall # the query to run to return the metric
    # metadata:           # optional, allows data source specific details to be passed
