apiVersion: blameless/v1alpha
kind: SLO # Service Level Objective

metadata:
  name: SLO Latency (sample 2)        # unique name of the SLO
  displayName: slo.yaml found at blameless-slo-samples/sample2 # optional

  userJourney: User Journey (sample 2) # name of the user journey to associate this SLO with - See spec for UserJourney

spec:
  description: "source: http://blamelesshq/blameless-slo-sample/sample2/slo.yaml" # optional - maps to user journey definition

  owner: nicolas@blameless.com       # name of a user in your Blmameless account (e.g. user email)

  # SLO status (required)
  #    Error budget notification policy activated only in Testing and Active mode.
  #    SLO settings can only be changed in Development and Testing mode via the Blameless web console.
  sloStatus: development              # possible values: development | testing | active

  sliName: SLI Availability (sample 2)     # name of the SLI to apply this SLO to

  # objective
  target:  0.99 # reliability target for this SLO - Possible values: numeric [0.0, 1.0)

  # required
  errorBudgetPolicyName: string # name of the error budget policy to attach to this SLO - See spec for AlertPolicy
