apiVersion: openslo/v1alpha
kind: AlertCondition

metadata:
  name: string
  displayName: string # optional

spec:
  description: # optional
  # severity: string # required (ticket or page) # Blameless: severity of an incident specified in the AlertNotification resource
  condition:
    kind: string      # ---> BLAMELESS: supported values are [percent_depleted | days_left]
    threshold: number # ---> BLAMELESS: percent_depleted [0.1 to 0.99999], days_left [0 to 27 days]

    # ---> BLAMELESS: The following parameters are not supported and ignored.
    # lookbackWindow: number
    # controlLookbackWindow: number # optional
    # alertAfter: number
