apiVersion: blameless/v1alpha
kind: Service

metadata:
  name: string        # unique name of the Service (group of SLIs)
  displayName: string # optional

spec:
  description: string
  notes: string       # optional
  owner: string       # required - name of a user in your Blmameless account (e.g. user email)
