apiVersion: blameless/v1alpha
kind: SLI # Service Level Indicator

metadata:
  name: SLI Saturation-datadog-saturation        # unique name of the SLI
  displayName: sli.yaml found at blameless-slo-samples/datadog/saturation # optional

  service: Service-datadog-saturation     # name of the service to associate this SLI with

spec:
  description: "source: http://blamelesshq/blameless-slo-sample/datadog/saturation/sli.yaml" # optional - maps to user SLI definition in Blameless

  owner: nicolas@blameless.com       # name of a user in your Blameless account (e.g. user email)

  sliType: saturation        # possible values: availability | latency | throughput | saturation
  
  thresholdMetric:        # represents the metric used to inform the SLO in the objectives stanza
    source: datadog     # data source for the metric
    queryType: string     # a name for the type of query to run on the data source
    query: (sum:datadog.estimated_usage.logs.ingested_bytes{*}.as_count() / sum:datadog.estimated_usage.logs.ingested_events{*}.as_count())*1073741824 # the query to run to return the metric
    # metadata:           # optional, allows data source specific details to be passed
