apiVersion: blameless/v1alpha
kind: SLI # Service Level Indicator

metadata:
  name: SLI Availability-datadog-availability        # unique name of the SLI
  displayName: sli.yaml found at blameless-slo-samples/datadog/availability # optional

  service: Service-datadog-availability     # name of the service to associate this SLI with

spec:
  description: "source: http://blamelesshq/blameless-slo-sample/datadog/availability/sli.yaml" # optional - maps to user SLI definition in Blameless

  owner: nicolas@blameless.com       # name of a user in your Blameless account (e.g. user email)

  sliType: availability        # possible values: availability | latency | throughput | saturation
  
  ratioMetric:
    good: # the numerator
      source: datadog    # data source for the metric
      queryType: string     # a name for the type of query to run on the data source
      query: avg:aws.apigateway.count{*}.as_count() - avg:aws.apigateway.5xxerror{*}.as_count() # the query to run to return the metric
      # metadata:             # optional, allows data source specific details to be passed
    total: # the denominator
      source: datadog    # data source for the metric
      queryType: string     # a name for the type of query to run on the data source
      query: avg:aws.apigateway.count{*}.as_count() # the query to run to return the metric
      # metadata:           # optional, allows data source specific details to be passed
