apiVersion: blameless/v1alpha
kind: SLO # Service Level Objective

metadata:
  name: SLO Availability-newrelic-availability        # unique name of the SLO
  displayName: slo.yaml found at blameless-slo-samples/newrelic/availability # optional

  userJourney: User Journey-newrelic-availability # name of the user journey to associate this SLO with - See spec for UserJourney

spec:
  description: "source: http://blamelesshq/blameless-slo-sample/newrelic/availability/slo.yaml" # optional - maps to user journey definition

  owner: nicolas@blameless.com       # name of a user in your Blmameless account (e.g. user email)

  # SLO status (required)
  #    Error budget notification policy activated only in Testing and Active mode.
  #    SLO settings can only be changed in Development and Testing mode via the Blameless web console.
  sloStatus: development              # possible values: development | testing | active

  sliName: SLI Availability-newrelic-availability              # name of the SLI to apply this SLO to

  # objective
  target:  70.0 # reliability target for this SLO - Possible values: numeric [0.0, 99.999)

  # required
  errorBudgetPolicyName: string # name of the error budget policy to attach to this SLO - See spec for AlertPolicy

  op: lt    
  value: 1        
  valueMetric: ms    